language: python
python:
 - "3.6"

services:
 - redis-server

install:
 - sudo apt-get update
 - sudo apt-get install yarn
 - pip install pipenv
 - pipenv install
 - yarn install

script:
 - python stubtradeapi/manage.py test
