language: python
python:
 - "3.6"
 
before_install:
 - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
 - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
 
install:
 - sudo apt-get update
 - sudo apt-get install yarn -y
 - pip install pipenv
 - pipenv install
 - yarn install

script:
 - python stubtradeapi/manage.py test
