# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('series', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('prev_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_traded_quantity', models.IntegerField()),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_trades', models.IntegerField()),
                ('deliverable_qty', models.IntegerField()),
                ('percent_del_to_trade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
