# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180408_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticks',
            unique_together=set([('symbol', 'date')]),
        ),
    ]
